spring:
  application:
    name: service-gateway-server
  profiles:
    active: development


---
# profile: common
spring:
  cloud:
    config:
      enabled: true

---
# profile: development
spring:
   config:
     activate:
         on-profile: development
     import: optional:configserver:http://localhost:7777
---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.7:7777